version: '3'

services:
  db:
    image: postgres
  
  redis:
    image: redis:alpine
    ports:
     - 6379:6379
    entrypoint: redis-server --appendonly yes
    restart: always

  django:
    build: 
      context: .
      dockerfile: ./docker/celeryapp/Dockerfile
    command: ./scripts/start.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  worker:
    build: 
      context: .
      dockerfile: ./docker/worker/Dockerfile
    # command: ./scripts/run_celery.sh
    volumes:
      - .:/worker
    depends_on:
      - db
      - redis

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - FLOWER_PORT=5555
    depends_on:
      - redis