version: '3'

services:
  db:
    image: postgres
  
  redis:
    image: redis
    ports:
     - 6379:6379
    entrypoint: redis-server --appendonly yes
    restart: always

  django:
    build: 
      context: .
      dockerfile: ./docker/celeryapp/Dockerfile
    command: ./start.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  worker:
    build: 
      context: .
      dockerfile: ./docker/worker/Dockerfile
    command: ./run_celery.sh
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  # flower:
  #   image: zoomeranalytics/flower:0.9.1-4.0.2
  #   restart: "no"
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - redis
  
  
