version: '3'

services:
  db:
    restart: always
    image: postgres
    env_file: 
      - .env
    expose: 
      - "5432"
  
  redis:
    image: redis:alpine
    ports:
     - 6379:6379
    entrypoint: redis-server --appendonly yes
    restart: always

  # rabbit:
  #   hostname: rabbit
  #   image: rabbitmq:3.6.0
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=mypass
  #   ports:
  #     - 5672:5672
  #     - 15672:15672

  django:
    restart: always
    container_name: django-celery
    build: 
      context: .
      dockerfile: ./docker/celeryapp/Dockerfile
    command: ./scripts/start.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      # - rabbit

  worker:
    build: 
      context: .
      dockerfile: ./docker/worker/Dockerfile
    command: ./scripts/run_celery_multi.sh
    volumes:
      - .:/worker
    depends_on:
      - db
      - redis
      # - rabbit

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://admin:mypass@rabbit:5672
      - FLOWER_PORT=5555
    links:
      - redis
      # - rabbit
    depends_on:
      - worker