# Generated by Django 2.2.5 on 2019-10-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeryapp', '0002_auto_20191022_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('finished', 'finished'), ('failed', 'failed')], default='pending', editable=False, max_length=20),
        ),
    ]
